### PR TITLE
os: fix get_raw_line for EOF on OpenBSD

### LINKED ISSUE #26361: v crash on OpenBSD with code sent from stdin
### Describe the bug

On OpenBSD/amd64, when trying to run V code sent via stdin, v compilation fails with panic.

### Reproduction Steps

- Build V from sources on OpenBSD/amd64 via `gmake rebuild` (GNU `make`)
- Try to run a simple V code sent from stdin: `echo "println(2+5)" | ./v run -`

### Expected Behavior

No error when running V code sent from stdin =>  V code compiles and runs as expected.

**OK on Linux Debian/amd64**
```sh
$ echo "println(2+5)" | ./v run -
7
```

### Current Behavior

Crash/Panic on OpenBSD/amd64:
```sh
$ echo "println(2+5)" | ./v run -
V panic: tos(): nil string
 v hash: 0e4ae76
    pid: 0x10fe9
    tid: 0x2f263da70
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:22255: at builtin___v_panic: Backtrace
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:22562: by builtin__tos
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:27218: by os__get_raw_line
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:27777: by os__get_raw_lines
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:27786: by os__get_raw_lines_joined
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:32116: by v__pref__parse_args_and_show_errors
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:63204: by main__main
/tmp/v_1000/v.01KF0H62NX48N498NN007C258H.tmp.c:64280: by main
```

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.5.0 0e4ae76

### Environment details (OS name and version, etc.)

|V full version      |V 0.5.0 0e4ae765077ea3c91fe30d904998a163d99293f3
|:-------------------|:-------------------
|OS                  |openbsd, 7.8, GENERIC.MP#192
|Processor           |4 cpus, 64bit, little endian
|Memory              |1.41GB/3.98GB
|                    |
|V executable        |/home/fox/dev/vlang.git/v
|V last modified time|2026-01-15 09:53:33
|                    |
|V home dir          |OK, value: /home/fox/dev/vlang.git
|VMODULES            |OK, value: /home/fox/.vmodules
|VTMP                |OK, value: /tmp/v_1000
|Current working dir |OK, value: /home/fox/dev/vlang.git
|                    |
|Git version         |git version 2.52.0
|V git status        |weekly.2026.03-20-g0e4ae765
|.git/config present |true
|                    |
|cc version          |OpenBSD clang version 19.1.7
|gcc version         |egcc (GCC) 11.2.0
|clang version       |OpenBSD clang version 19.1.7
|tcc version         |tcc version 0.9.28rc 2025-05-27 HEAD@cb39bc4c (x86_64 OpenBSD)
|tcc git status      |thirdparty-openbsd-amd64 200e7752
|emcc version        |N/A
|glibc version       |N/A

### PR DESCRIPTION
**Pull request by lcheylus**
On OpenBSD, at the end of file, pointer `buf=0` after call of `C.getline` => `tos` function panic.

Add case for error when calling `C.getline`

Fix #26361 and #26014

---
**Tests OK on OpenBSD and Linux** with V code sent from `stdin`
```sh
$ uname -mrs
OpenBSD 7.8 amd64
$ echo "println(2+5)" | ./v run -
7

$ uname -mrs
Linux 6.12.38+deb13-amd64 x86_64
$ echo "println(2+5)" | ./v run -
7
```

### CODE REVIEW

File: vlib/os/os.c.v [hunk 1]
```diff
@@ -615,8 +615,21 @@ pub fn get_raw_line() string {
...
+
+		mut str := ''
 		nr_chars := unsafe { C.getline(voidptr(&buf), &max, C.stdin) }
-		str := unsafe { tos(buf, if nr_chars < 0 { 0 } else { nr_chars }) }
+		// On OpenBSD, buf=0 for EOF =>  panic when calling tos function
+		$if openbsd {
+			if nr_chars != -1 {
+				str = unsafe { tos(buf, nr_chars) }
+			} else {
+				if int(C.feof(C.stdin)) == 0 && int(C.ferror(C.stdin)) != 0 {
```
Comment (spytheman) [inline vlib/os/os.c.v:626]: why panic, could it not just not modify str in this case (since it is already an empty string)?

**Comment by lcheylus** [comment]
@spytheman To create a PR to fix #26344, please I need a review and merge/commit if OK.

**Comment by spytheman** [comment]
> @spytheman To create a PR to fix #26344, please I need a review and merge/commit if OK.

Sorry, I reviewed it yesterday, but it was in a `Pending` state according to the web UI 🤔 .
I think it is good to merge, but that it can be also simplified by removing the panic, and just returning `''` in that case ('' is different from an empty line, which will have the '\n' character in it).

File: vlib/os/os.c.v (hunk 1 above)
Comment (lcheylus) [reply vlib/os/os.c.v:626]: No, in this case, there is an error when reading line via `C.getline` (`ferror != 0`) and not EOF ; input could be `!= ''`  => we must exit with `panic`.

See https://man.openbsd.org/getline for detailed explanations about `getline` on OpenBSD (different from Linux version).
