### PR TITLE
cgen: fix auto str for array and map for C struct

### LINKED ISSUE #22379: Printing struct with c alias map gives c compiler error: 'indent_struct' undeclared
**V doctor:**
```
V full version: V 0.4.8 18eee34.1b812f6
OS: windows, Microsoft Windows 11 Pro v22631 64-bit
Processor: 24 cpus, 64bit, little endian, 

getwd: D:\vbug2
vexe: C:\v\v.exe
vexe mtime: 2024-10-01 06:01:23

vroot: OK, value: C:\v
VMODULES: OK, value: C:\Users\info\.vmodules
VTMP: OK, value: C:\Users\info\AppData\Local\Temp\v_0

Git version: git version 2.42.0.windows.2
Git vroot status: 0.4.8-10-g1b812f6b-dirty
.git/config present: true

CC version: Error: 'cc' is not recognized as an internal or external command,

operable program or batch file.


thirdparty/tcc status: thirdparty-windows-amd64 b425ac82

```

**What did you do?**
`./v -g -o vdbg cmd/v && ./vdbg main.v`
```v
module main

import sokol.gfx

struct GameObject  {
mut:
	shader_cache    map[string]gfx.Pipeline
}

fn main() {
	g := GameObject{}
	println(g)
}

```

**What did you expect to see?**

no c error

**What did you see instead?**
```
================== C compilation error (from tcc): ==============
cc: C:/v/thirdparty/sokol/sokol_app.h:7834: warning: implicit declaration of function 'freopen_s'
cc: C:/Users/info/AppData/Local/Temp/v_0/main.01J93DP44V8CYN34300JY0EJ37.tmp.c:2988: error: 'indent_struct' undeclared
... (the original output was 8 lines long, and was truncated to 2 lines)
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
```
> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

### PR DESCRIPTION
**Pull request by felipensp**
Fix #22379

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmZiZWY2MjQzYjBiYWU0OTU5ZTI5MDAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.6ipcZG_zoeMbNmZ5DoXX7L_Y_QBJ1PhNzskvVw_Shog">Huly&reg;: <b>V_0.6-20843</b></a></sub>

### CODE REVIEW

File: vlib/v/tests/c_structs/cstruct_arr_map_test.c.v [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+	assert g.c.len == 2
+	assert g.c[0] != none
+	assert g.c[1] == none
+
+	t := ?Foo{
+		a: 123
+	}
+	dump(t)
+	assert t?.a == 123
+}
```
Comment (spytheman) [inline vlib/v/tests/c_structs/cstruct_arr_map_test.c.v:46]: Please put some assertions against the contents of `g.str()` and `t.str()` too.

Comment (spytheman) [reply vlib/v/tests/c_structs/cstruct_arr_map_test.c.v:46]: (something like `assert g.str().contains('a: 100')` etc)
