### PR TITLE
cgen: fix missing return code generated

### LINKED ISSUE #22838: Returning a `return` strange behaviour
### Describe the bug

When a programmer by mistake use a twice unnecessary `return` statement within a ` return if { } else { }` block, the code is accepted and the result is not logic.

### Reproduction Steps

```v
fn empty(s string) !string {
	return if s != '' {
		s
	} else {
		//error('empty') // This works
		return error('empty') // This "double" return FAILS
	}
}

str_1 := empty('something') or {
	assert false, 'something is not empty!'
	return
}
assert str_1 == 'something'

str_2 := empty('') or {
	println('expected error ${err}')
	return
}
assert false, 'invalid accepted ${str_2}'
```

### Expected Behavior

Maybe first prevent the second `return` can be compiled or that `return return error('message')` worked as `return error('message')`.

### Current Behavior

```
code.v:20:NaN: fn main.main: assert false, 'invalid accepted $str_2'
      message: invalid accepted �
```

Seems the error is not returned but is returned a pointer to `return error('something')`.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### V version

V 0.4.8 5092626

### Environment details (OS name and version, etc.)

https://play.vlang.io/p/6c8f09ab31

> [!NOTE]
> You can use the 👍 reaction to increase the issue's priority for developers.
>
> Please note that only the 👍 reaction to the issue itself counts as a vote.
> Other reactions and those to comments will not be taken into account.

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMyOTIxMWU3Y2M1YTc4NTQyYjFkYWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.2TReIwSmUoipbtIAossPj7pECgSEZBIjmKW346ld9Ws">Huly&reg;: <b>V_0.6-21283</b></a></sub>

### PR DESCRIPTION
**Pull request by felipensp**
Fix #22838

<sub><a href="https://huly.app/guest/vlang-66f40c4d-a476b54c67-771fdd?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMyYzA5NmU3Y2M1YTc4NTQyYjQwOTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctYWxleGFuZGVyLXZsYW5nLTY2ZjQwYzRkLWE0NzZiNTRjNjctNzcxZmRjIn0.1J9fbK_6LL9-824Ly15f1e7YSOYNttNpT_rjWldJUt8">Huly&reg;: <b>V_0.6-21284</b></a></sub>

### CODE REVIEW

File: vlib/v/gen/c/testdata/if_else_return.c.must_have [hunk 1]
```diff
@@ -0,0 +1,10 @@
+VV_LOCAL_SYMBOL _result_string main__empty(string s) {
+_result_string _t2; /* if prepend */
+if ((s).len != 0) {
+_result_ok(&(string[]) { s }, (_result*)(&_t2), sizeof(string));
+} else {
+return (_result_string){ .is_error=true, .err=_v_error(_SLIT("empty")), .data={EMPTY_STRUCT_INITIALIZATION} };
```
Comment (spytheman) [inline vlib/v/gen/c/testdata/if_else_return.c.must_have:6]: Afaik just this line matters, the rest can make the test more brittle.
Am I missing something?

**Review by spytheman — APPROVED** [review]
Excellent work.
