### PR TITLE
picoev, picohttparser: reimplementation in V

### LINKED ISSUE #18291: Compiling examples/pico/pico.v still fails on Windows
### Describe the bug

I am trying to run the pico.v example from v/examples/pico/pico.v, but it doesn't work on Windows

### Expected Behavior

I expected the pico.v file to compile and run correctly without any issues.

### Current Behavior

When I try to run the pico.v example using:
v run pico.v
I get the following output:
C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picohttpparser/picohttpparser.c:19: warning: assignment from incompatible pointer type
C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picohttpparser/picohttpparser.c:19: warning: assignment from incompatible pointer type

In file included from C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picoev/picoev.c:8:
C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picoev/src/picoev_select.c:75: warning: function might return no value: 'picoev_w32_init'
C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picoev/src/picoev.h:143: warning: cast between pointer and integer of different size
C:/Users/tudor/Documents/v_windows_1/v/thirdparty/picoev/src/picoev.h:143: warning: cast between pointer and integer of different size

builder error: 'netinet/tcp.h' not found

### Reproduction Steps

The code inside the v/examples/pico/pico.v file:
```v
import json
import picoev
import picohttpparser

const (
	port = 8088
)

struct Message {
	message string
}

[inline]
fn json_response() string {
	msg := Message{
		message: 'Hello, World!'
	}
	return json.encode(msg)
}

[inline]
fn hello_response() string {
	return 'Hello, World!'
}

fn callback(data voidptr, req picohttpparser.Request, mut res picohttpparser.Response) {
	if picohttpparser.cmpn(req.method, 'GET ', 4) {
		if picohttpparser.cmp(req.path, '/t') {
			res.http_ok()
			res.header_server()
			res.header_date()
			res.plain()
			res.body(hello_response())
		} else if picohttpparser.cmp(req.path, '/j') {
			res.http_ok()
			res.header_server()
			res.header_date()
			res.json()
			res.body(json_response())
		} else {
			res.http_404()
		}
	} else {
		res.http_405()
	}
	res.end()
}

fn main() {
	println('Starting webserver on http://127.0.0.1:${port}/ ...')
	picoev.new(port: port, cb: &callback).serve()
}
```
Reproduction steps in Command Prompt:
C:\Users\tudor\Documents\v_windows_1\v\examples\pico>v run pico.v

### Possible Solution

The header file <netinet/tcp.h> is required by picoev, but it was not found.
Perhaps you can add it in V's thirdparty folder?
Or you can explain me where to get the header file from. That is the only possible solution I can think of at the moment.

### Additional Information/Context

As I said, the header file <netinet/tcp.h> is not available on my machine.

### V version

V 0.3.4 80d404c

### Environment details (OS name and version, etc.)

V full version: V 0.3.4 e2f18fc.80d404c
OS: windows, Microsoft Windows 10 Home v19045 64-bit
Processor: 4 cpus, 64bit, little endian,

getwd: C:\Users\tudor\Documents\v_windows_1\v\examples\pico
vexe: C:\Users\tudor\Documents\v_windows_1\v\v.exe
vexe mtime: 2023-05-28 08:25:53

vroot: OK, value: C:\Users\tudor\Documents\v_windows_1\v
VMODULES: OK, value: C:\Users\tudor\.vmodules
VTMP: OK, value: C:\Users\tudor\AppData\Local\Temp\v_0

Git version: git version 2.39.0.windows.1
Git vroot status: weekly.2023.15-207-g80d404c2
.git/config present: true

CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version
thirdparty/tcc: N/A

### PR DESCRIPTION
**Pull request by Casper64**
Reimplement the picoev and picohttpparser module in V.

fix #18291 #7703

This pullrequest aims to reimplement the picoev and picohttpparser module in V. If it's fully written in V it is easier to contribute for others to improve the module. It will also get rid of a third party depency.

Currently the module works on Linux with `epoll` and on windows with `select`. 
The `select` version works on all platforms that support select but for now it's exclusive to windows for testing purposes.

## Usage

```v
module main

import picoev
import picohttpparser
import net.http

fn main() {
	mut server := picoev.new(picoev.Config{
		cb: handle_request
	})
	server.serve()
}

fn handle_request(userdata voidptr, req picohttpparser.Request, mut res picohttpparser.Response) {
	res.http_ok()
	res.html()
	res.body('Hello Picoev!')
	res.end()
}
```

## Performance

Performance is as fast, if not faster, as with the C implementation

## TODO:

- [X] Implemt epoll for (linux)
- [X] Implement select for windows
- [X] Implement kqueue
- [x] Make select also available for unix systems.
- [ ] Make kqueue available on all operating systems that support it.
- [x] Reimplement `picohttparser.Request` in V

And other optimizations.

## Contribution needed

I am working on the `kqueue` implementation, but since I don't own a mac I can't test it on macos 🥲 

### <samp>🤖 Generated by Copilot at a19651c</samp>

This pull request implements a custom Picoev struct and event loop for the picoev library, and improves the Windows compatibility of the picohttpparser library. It refactors the `picoev.v` file and adds the `multiplex_linux.v` and `multiplex_windows.v` files for different event loop implementations. It also changes the `response.v` file to use the C.send function for sending data.

### <samp>🤖 Generated by Copilot at a19651c</samp>

*  Add epoll-based event loop for Linux systems ([link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-0dcab29ae7dcdf3209d9d60cdbd7132cef04561b235df1b537fe151ffcfdfc89R1-R137))
* Add select-based event loop for Windows and other systems ([link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-d13c244045d70eebafa0ae8efb7598523851acbcffa79716010b779381d8efdcR1-R97))
* Refactor `picoev.v` file to use Picoev struct and methods instead of C.picoev functions and types ([link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL1-L3),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL10-R33),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL65-R218),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL99-R262),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL143-R313),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL182-R322),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL204-R352),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cR361),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL236-R370),[link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-adc0159bf9f9b9fb9b3a6cbbd0e026447828931e20d52c58fcc10bcc0daa3b1cL247-R402))
* Update `response.v` file to use C.send function instead of C.write function for Windows compatibility ([link](https://github.com/vlang/v/pull/18506/files?diff=unified&w=0#diff-eb188c7b1db2171c9e45ee93acfc7b590ba2b63525a6303ac0f57bd2cac45ad7L110-R111))

### CODE REVIEW

**Comment by JalonSolov** [comment]
Can you also refactor the `C.` stuff into `.c.v` files?

File: vlib/picoev/loop_freebsd.c.v [hunk 1]
```diff
@@ -47,8 +47,9 @@ fn create_kqueue_loop(id int) !&KqueueLoop {
 	return loop
 }
 
+// ev_set sets a new `kevent` with file descriptor `index`
 [inline]
-pub fn (mut pv Picoev) ev_set(index int, operation int, events int) {
```
Comment (spytheman) [inline vlib/picoev/loop_freebsd.c.v]: Would not that method be useful as a `pub` in the future as well?

**Comment by JalonSolov** [comment]
Any benchmarks available?  It would be interesting to see, even if only for intermediate changes.

Of course the code can always be optimized later (and the benchmarks could be run twice... once normally, and once with `-prod`).

**Comment by Casper64** [comment]
@JalonSolov I've done quite some testing for fun. Below are some benchmarks using [wrk](https://github.com/wg/wrk) and [baton](https://github.com/americanexpress/baton) (a go testing tool).

For each benchmark I took the best out of 3. 
Everything is tested on linux WSL2 since the old Picoev didn't work with Windows and I don't own a mac :). 
CPU: Intel Core i9 12900K (24 threads).

## Summary

V version is slightly faster with `-prod`, but slower without `-prod`.

Memory usage is the 1-4mb higher on the new version.

## Sending connections from multiple threads.
I found that `wrk` results differ too much on each run when sending requests from multiple threads, that is why I used baton to benchmark sending connections from multiple threads.

### Command used
sending requests from 100 concurrent connections for 30 seconds, with goroutines so covering multiple threads.
```
baton -z requests.csv -c 100 -t 30
```

`requests.csv`
```
GET,http://127.0.0.1:8088/,,,
GET,http://127.0.0.1:8088/t,,,
```

### Old

**With prod:**
```
└─$ baton -z requests.csv -c 100 -t 30
Configuring to send requests from file. (Read 2 requests)
Generating the requests...
Finished generating the requests
Sending the requests to the server...
Finished sending the requests
Processing the results...


====================== Results ======================
Total requests:                              10413565
Time taken to complete requests:        30.003644803s
Requests per second:                           347077
===================== Breakdown =====================
Number of connection errors:                        0
Number of 1xx responses:                            0
Number of 2xx responses:                     10413565
Number of 3xx responses:                            0
Number of 4xx responses:                            0
Number of 5xx responses:                            0
=====================================================
```

**Without prod:**
```
└─$ baton -z requests.csv -c 100 -t 30
Configuring to send requests from file. (Read 2 requests)
Generating the requests...
Finished generating the requests
Sending the requests to the server...
Finished sending the requests
Processing the results...


====================== Results ======================
Total requests:                               9331613
Time taken to complete requests:        30.003814517s
Requests per second:                           311014
===================== Breakdown =====================
Number of connection errors:                        0
Number of 1xx responses:                            0
Number of 2xx responses:                      9331613
Number of 3xx responses:                            0
Number of 4xx responses:                            0
Number of 5xx responses:                            0
=====================================================
```


### New

**With prod:**
```
└─$ baton -z requests.csv -c 100 -t 30
Configuring to send requests from file. (Read 2 requests)
Generating the requests...
Finished generating the requests
Sending the requests to the server...
Finished sending the requests
Processing the results...


====================== Results ======================
Total requests:                              10713605
Time taken to complete requests:        30.003676865s
Requests per second:                           357076
===================== Breakdown =====================
Number of connection errors:                        0
Number of 1xx responses:                            0
Number of 2xx responses:                     10713605
Number of 3xx responses:                            0
Number of 4xx responses:                            0
Number of 5xx responses:                            0
=====================================================
```

**Without prod:**
```
└─$ baton -z requests.csv -c 100 -t 30
Configuring to send requests from file. (Read 2 requests)
Generating the requests...
Finished generating the requests
Sending the requests to the server...
Finished sending the requests
Processing the results...


====================== Results ======================
Total requests:                               7962170
Time taken to complete requests:          30.0039103s
Requests per second:                           265371
===================== Breakdown =====================
Number of connection errors:                        0
Number of 1xx responses:                            0
Number of 2xx responses:                      7962170
Number of 3xx responses:                            0
Number of 4xx responses:                            0
Number of 5xx responses:                            0
=====================================================
```

## Sending connections from a single thread
Since Picoev is a single threaded application it is fair to also test the performance when connections come from a single thread.

### Command used
sending requests from 1000 concurrent connections for 30 seconds from a single thread.

```
wrk -t 1 -c 1000 http://127.0.0.1:8088/ -d 30s
```

### Old

**With prod:**
```
─$ wrk -t 1 -c 1000 http://127.0.0.1:8088/ -d 30s
Running 30s test @ http://127.0.0.1:8088/
  1 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.52ms  393.04us   6.40ms   87.68%
    Req/Sec     1.05M    29.71k    1.11M    87.96%
  31201845 requests in 30.08s, 2.27GB read
Requests/sec: 1037353.59
Transfer/sec:     77.17MB
```

### New

**With prod:**
```
└─$ wrk -t 1 -c 1000 http://127.0.0.1:8088/ -d 30s
Running 30s test @ http://127.0.0.1:8088/
  1 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.48ms  329.80us   6.83ms   90.04%
    Req/Sec     1.05M    33.61k    1.11M    85.95%
  31447155 requests in 30.08s, 2.28GB read
Requests/sec: 1045538.12
Transfer/sec:     77.77MB
```

## Windows
For the windows fans: select could only handle 20 concurrent connections much more and the program segfaults. I tried increasing the maximum open file descriptors and turning of defender, but it seems this is "just windows".

```
>baton.exe -z requests.csv -c 20 -t 30
Configuring to send requests from file. (Read 2 requests)
Generating the requests...
Finished generating the requests
Sending the requests to the server...
Finished sending the requests
Processing the results...


====================== Results ======================
Total requests:                               3333825
Time taken to complete requests:          30.0013945s
Requests per second:                           111122
===================== Breakdown =====================
Number of connection errors:                        0
Number of 1xx responses:                            0
Number of 2xx responses:                      3333825
Number of 3xx responses:                            0
Number of 4xx responses:                            0
Number of 5xx responses:                            0
=====================================================
```

**Comment by JalonSolov** [comment]
Very nice numbers!

**Review by S-YOU — APPROVED** [review]
Awesome work!

**Comment by S-YOU** [comment]
> I found that wrk results differ too much on each run when sending requests from multiple threads, that is why I used baton to benchmark sending connections from multiple threads.

I think if you use taskset on linux for multithreaded version, you could probably get better results, like 10 cpus to server and 14 cpus to wrk, for example (for 24 cpus machine).

taskset -c 14-23 ./server ...
taskset -c 0-13 wrk ...

File: vlib/picohttpparser/picohttpparser.v [hunk 2]
```diff
@@ -102,10 +102,10 @@ fn (mut r Request) phr_parse_request_path_pipeline(buf_start &u8, buf_end &u8, m
 	}
 
 	pret.ret = -1
-	return
+	return error('error parsing request: no request foud')
```
Comment (JalonSolov) [inline vlib/picohttpparser/picohttpparser.v:105]:
```suggestion
	return error('error parsing request: no request found')
```

File: vlib/picohttpparser/picohttpparser.v [hunk 3]
```diff
@@ -160,21 +160,21 @@ fn (mut r Request) phr_parse_request(buf_start &u8, buf_end &u8, mut pret Pret)
...
-			return unsafe { nil }
+			return error('error parsing request: expected "\n" after "\r"')
 		}
 		unsafe { buf++ }
 	} else if *buf == `\n` {
 		unsafe { buf++ }
 	} else {
 		pret.ret = -1
-		return unsafe { nil }
+		return error('error parsing request: no newline after http version')
```
Comment (JalonSolov) [inline vlib/picohttpparser/picohttpparser.v:170]: Perhaps `EOL` instead of `newline`, since it should always be carriage return + newline (\r\n)?

Comment (JalonSolov) [reply vlib/picohttpparser/picohttpparser.v:170]: Or just `"\r\n"` as you use in a later message.

**Comment by spytheman** [comment]
@Casper64 is there a performance impact from the last commit fcb5673 ?

I am mostly curious, because of this:
```
- fn (mut r Request) phr_parse_request_path(buf_start &u8, buf_end &u8, mut pret Pret) {
+ fn (mut r Request) phr_parse_request_path(buf_start &u8, buf_end &u8, mut pret Pret) ! {
```

**Comment by Casper64** [comment]
@spytheman interestingly the performance difference is very minimal (1-2%) when the request parsing is done inside the `picoev` loop, which I tested yesterday.

However I just did some benchmarking with plain parsing the request and that’s almost 2 times slower 🤯, so I will revert the change.

**Comment by spytheman** [comment]
@Casper64 can it be merged as it is?

**Comment by Casper64** [comment]
> @Casper64 can it be merged as it is?

Should the thirdparty dependency be removed in this pr? If no then it can be merged.

**Comment by JalonSolov** [comment]
Baby steps.  I'd say merge this, and do another PR to clean it up, optimize it, or whatever.  Can also wait for the Mac kqueue support, etc.

**Comment by spytheman** [comment]
I am merging it, since it is already quite useful on Linux as it is.

**Comment by Casper64** [comment]
@JalonSolov I'll update the pr description, but mac is supported as is freebsd with kqueue. Any other OS apart from linux will use select.
