### PR TITLE
parser: add unused variable warning

### LINKED ISSUE #4208: Unused variable warning / error is broken
**V version:** 0.1.26 83289d7.07c53b1
**OS:** Ubuntu X86_64

**What did you do?**
Executed this code:
`v run hello_world.v`
```V
fn main() {
    age := 21
}
```

**What did you expect to see?**
Unused variable warning.
 
**What did you see instead?**
Nothing

-----------

Also no error is displayed when the `-prod` option is passed (`v -prod run hello_world.v`).

### PR DESCRIPTION
**Pull request by krischerven**
fixes #4208

the warning is an error on `v -prod`

### CODE REVIEW

File: vlib/builtin/builtin_windows.c.v [hunk 1]
```diff
@@ -82,6 +82,8 @@ $if msvc {
 	defer { C.SymCleanup(handle) }
 
 	options := C.SymSetOptions(SYMOPT_DEBUG | SYMOPT_LOAD_LINES | SYMOPT_UNDNAME)
+	_ = options
```
Comment (alexesprit) [inline vlib/builtin/builtin_windows.c.v:85]: If you don't need a return value, you can omit it.

Please use `C.SymSetOptions(SYMOPT_DEBUG | SYMOPT_LOAD_LINES | SYMOPT_UNDNAME)` instead.

File: vlib/v/checker/tests/inout/match_expr_else.vv [hunk 2]
```diff
@@ -10,4 +10,5 @@ fn main() {
 			'string'
 		}
 	}
+	_ = res
```
Comment (alexesprit) [inline vlib/v/checker/tests/inout/match_expr_else.vv:13]: You can use `_` directly instead of `res` in `match` statement, or even skip it (this is better, if it won't break tests).

File: vlib/builtin/builtin_windows.c.v (hunk 1 above)
Comment (krischerven) [reply vlib/builtin/builtin_windows.c.v:85]: Will do.

File: vlib/v/checker/tests/inout/match_expr_else.vv (hunk 2 above)
Comment (krischerven) [reply vlib/v/checker/tests/inout/match_expr_else.vv:13]: Are you sure that won't result in the function being removed in the generated C code? @alexesprit

File: vlib/builtin/builtin_windows.c.v (hunk 1 above)
Comment (krischerven) [reply vlib/builtin/builtin_windows.c.v:85]: Actually, does this need to be in here at all? From what I can tell it doesn't have any side effects.

File: vlib/v/checker/tests/inout/match_expr_else.vv (hunk 2 above)
Comment (alexesprit) [reply vlib/v/checker/tests/inout/match_expr_else.vv:13]: Why should this function be removed?

Comment (krischerven) [reply vlib/v/checker/tests/inout/match_expr_else.vv:13]: I believe gcc removes dead code when it has certain flags turned on

**Comment by medvednikov** [comment]
Isn't it easier to just use var.is_used? @joe-conigliaro what do you think?

File: vlib/builtin/builtin_windows.c.v (hunk 1 above)
Comment (alexesprit) [reply vlib/builtin/builtin_windows.c.v:85]: What do you mean? If you're talking about `SymSetOptions` function, yes it should be called. But a return value of this function is not used.

File: vlib/v/checker/tests/inout/match_expr_else.vv (hunk 2 above)
Comment (alexesprit) [reply vlib/v/checker/tests/inout/match_expr_else.vv:13]: This code isn't supposed to be compiled by V, so `gcc` won't remove dead code.

Plus, it's still dead code, as the `res` variable is not used, and that means the whole match statement is useless. Compilers are smart to find such cases.

Comment (krischerven) [reply vlib/v/checker/tests/inout/match_expr_else.vv:13]: Alright, I'll remove these instances.

**Comment by medvednikov** [comment]
@krischerven 

Doesn't seem to be triggered in 

```
fn main() {
        a:=1
        println('hi')
}
```

**Comment by krischerven** [comment]
@medvednikov weird, it works for me

```
unusedvartest.v:2:9: error: Unused variable: a 
    1| fn main() {
    2|         a:=1
               ^
    3|         println('hi')
    4| }
```

**Comment by medvednikov** [comment]
Never mind, it works :)

Sorry

**Comment by krischerven** [comment]
No problem
