### PR TITLE
os: fix rare crash in read_file. Fix #12052

### LINKED ISSUE #12052: C.ftell can return very high values that results in "dangerous" values if cast
I've had a strange, but reproducible, crash occurring in [tipsy](https://github.com/Larpon/tipsy) on my own desktop.

It's hard for me to recreate and reproduce a test everyone can try since it's occurring in a special condition where `C.ftell()` will report an extremely high value (`9223372036854775807`) and an `int(...)` cast will turn that value into `-1` - resulting in a value of `0` getting passed to `malloc_noscan` in the body of `os.read_file()`. I haven't been able to get `C.ftell` to report this high value under normal test conditions. And I can't screen record it either since it's trigger by something my lock-screen causes :grimacing: .

Original panic message (constructed from memory):
```
V panic: > V malloc(<=0)
v hash: 10caf4a
/dev/shm/v/syncs.11864338658699659981.tmp.c:7386: at _v_panic: Backtrace
/dev/shm/v/syncs.11864338658699659981.tmp.c:18567: by builtin__malloc_noscan
/dev/shm/v/syncs.11864338658699659981.tmp.c:12989: by os__read_file
/dev/shm/v/syncs.11864338658699659981.tmp.c:17739: by main__main
/dev/shm/v/syncs.11864338658699659981.tmp.c:18136: by main
```

After I traced it down and modified `os.c.v` to output this in a panic, I could see the problem:
`fsize` is large and the `-1` is the cast value. This results in a call to `malloc_noscan(0)` that then panics.
```
V panic: can not allocate 0 bytes. (fsize: 9223372036854775807 / -1)
v hash: 10caf4a
/dev/shm/v/syncs.11864338658699659981.tmp.c:7386: at _v_panic: Backtrace
/dev/shm/v/syncs.11864338658699659981.tmp.c:12989: by os__read_file
/dev/shm/v/syncs.11864338658699659981.tmp.c:17739: by main__main
/dev/shm/v/syncs.11864338658699659981.tmp.c:18136: by main
```

It can probably be reproduced by others since I'm able to reproduce it via tipsy on Kubuntu 18.04.

Tipsy will crash when the desktop locks the session and show the lock screen. This gives a condition where calling `os.read_file()` causes the condition above.

***edit*** I've provided a fix in #12052 that checks the result value of the cast.
***edit*** It can probably also be reproduced by passing a gigabytes sized file to `os.read_file` since C.ftell will then report a value in the 64-bit range.

### PR DESCRIPTION
**Pull request by Larpon**
This PR fixes the rare crash described in #12052

### CODE REVIEW

**Comment by Larpon** [comment]
After further investigation it's really just an effect of casting `i64` to `int` without checking the result of the cast.

File: vlib/os/os.c.v [hunk 1]
```diff
@@ -86,13 +86,19 @@ pub fn read_bytes(path string) ?[]byte {
...
+	len := int(fsize)
+	// On some systems C.ftell can return values in the 64-bit range
+	// that, when cast to `int`, can result in values below 0.
+	if len < 0 {
+		return error('$fsize cast to int results in ${int(fsize)})')
+	}
 	C.rewind(fp)
-	mut res := []byte{len: int(fsize)}
+	mut res := []byte{len: len}
 	nr_read_elements := int(C.fread(res.data, fsize, 1, fp))
```
Comment (spytheman) [inline vlib/os/os.c.v:97]: `fsize` should be `len` here too, otherwise reading from a big file, can still lead to overflowing the allocated buffer in `res.data`. For example if fsize is `5 000 000 000`, then  len := int(5000000000) == 705032704, which is still positive.

Comment (Larpon) [reply vlib/os/os.c.v]: fixed in 19a50e9b9

File: vlib/os/os.c.v [hunk 2]
```diff
@@ -86,13 +86,19 @@ pub fn read_bytes(path string) ?[]byte {
 	if fsize < 0 {
 		return error('ftell failed')
 	}
+	len := int(fsize)
+	// On some systems C.ftell can return values in the 64-bit range
+	// that, when cast to `int`, can result in values below 0.
+	if len < 0 {
```
Comment (spytheman) [inline vlib/os/os.c.v:92]: I think a better check would be `if i64(len) < fsize {`, since that will work for all values.
For example, this:
```v
for fsize := i64(0);; fsize+=100_000_000 {
	if 0 == fsize % 500_000_000 {
		len := int(fsize)
		println('> fsize: ${fsize:12} | len: ${len:12}')
		if fsize > 10000000000 {
			break
		}
	}
}
```
produces:

```
> fsize:            0 | len:            0
> fsize:    500000000 | len:    500000000
> fsize:   1000000000 | len:   1000000000
> fsize:   1500000000 | len:   1500000000
> fsize:   2000000000 | len:   2000000000
> fsize:   2500000000 | len:  -1794967296
> fsize:   3000000000 | len:  -1294967296
> fsize:   3500000000 | len:   -794967296
> fsize:   4000000000 | len:   -294967296
> fsize:   4500000000 | len:    205032704
> fsize:   5000000000 | len:    705032704
> fsize:   5500000000 | len:   1205032704
> fsize:   6000000000 | len:   1705032704
> fsize:   6500000000 | len:  -2089934592
> fsize:   7000000000 | len:  -1589934592
> fsize:   7500000000 | len:  -1089934592
> fsize:   8000000000 | len:   -589934592
> fsize:   8500000000 | len:    -89934592
> fsize:   9000000000 | len:    410065408
> fsize:   9500000000 | len:    910065408
> fsize:  10000000000 | len:   1410065408
> fsize:  10500000000 | len:   1910065408
```

File: vlib/os/os.c.v [hunk 3]
```diff
@@ -113,8 +119,14 @@ pub fn read_file(path string) ?string {
...
+	allocate := int(fsize)
+	// On some systems C.ftell can return values in the 64-bit range
+	// that, when cast to `int`, can result in values below 0.
+	if allocate < 0 {
+		return error('$fsize cast to int results in ${int(fsize)})')
+	}
 	unsafe {
-		mut str := malloc_noscan(int(fsize) + 1)
+		mut str := malloc_noscan(allocate + 1)
 		nelements := int(C.fread(str, 1, fsize, fp))
```
Comment (spytheman) [inline vlib/os/os.c.v:130]: `fsize` -> `allocate`

File: vlib/os/os.c.v (hunk 2 above)
Comment (Larpon) [reply vlib/os/os.c.v]: Cool. Done in defd894

File: vlib/os/os.c.v (hunk 3 above)
Comment (Larpon) [reply vlib/os/os.c.v]: Done in defd894

**Review by spytheman — APPROVED** [review]
